# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'BLDCjVFJBw.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1145, 666)
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1131, 591))
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.groupBox = QGroupBox(self.tab_1)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 20, 561, 241))
        font = QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.I_PolePair_1 = QSpinBox(self.groupBox)
        self.I_PolePair_1.setObjectName(u"I_PolePair_1")
        self.I_PolePair_1.setGeometry(QRect(360, 30, 91, 21))
        self.I_PolePair_1.setValue(2)
        self.R_MagnetRadialLength_1 = QDoubleSpinBox(self.groupBox)
        self.R_MagnetRadialLength_1.setObjectName(u"R_MagnetRadialLength_1")
        self.R_MagnetRadialLength_1.setGeometry(QRect(360, 60, 91, 21))
        self.R_MagnetRadialLength_1.setDecimals(4)
        self.R_MagnetRadialLength_1.setSingleStep(0.000100000000000)
        self.R_MagnetRadialLength_1.setValue(0.038300000000000)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 151, 21))
        self.I_PolePair_2 = QSpinBox(self.groupBox)
        self.I_PolePair_2.setObjectName(u"I_PolePair_2")
        self.I_PolePair_2.setGeometry(QRect(460, 30, 91, 21))
        self.I_PolePair_2.setValue(2)
        self.R_MagnetRadialLength_unit = QComboBox(self.groupBox)
        self.R_MagnetRadialLength_unit.addItem("")
        self.R_MagnetRadialLength_unit.addItem("")
        self.R_MagnetRadialLength_unit.addItem("")
        self.R_MagnetRadialLength_unit.setObjectName(u"R_MagnetRadialLength_unit")
        self.R_MagnetRadialLength_unit.setGeometry(QRect(280, 60, 71, 21))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 60, 151, 21))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 90, 151, 21))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 120, 231, 21))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 150, 151, 21))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 180, 151, 21))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 210, 151, 21))
        self.R_MagnetRadialLength_2 = QDoubleSpinBox(self.groupBox)
        self.R_MagnetRadialLength_2.setObjectName(u"R_MagnetRadialLength_2")
        self.R_MagnetRadialLength_2.setGeometry(QRect(460, 60, 91, 21))
        self.R_MagnetRadialLength_2.setDecimals(4)
        self.R_MagnetRadialLength_2.setSingleStep(0.000100000000000)
        self.R_MagnetRadialLength_2.setValue(0.038300000000000)
        self.R_MagnetOutR_2 = QDoubleSpinBox(self.groupBox)
        self.R_MagnetOutR_2.setObjectName(u"R_MagnetOutR_2")
        self.R_MagnetOutR_2.setGeometry(QRect(460, 90, 91, 21))
        self.R_MagnetOutR_2.setDecimals(4)
        self.R_MagnetOutR_2.setSingleStep(0.000100000000000)
        self.R_MagnetOutR_2.setValue(0.128200000000000)
        self.R_MagnetOutR_unit = QComboBox(self.groupBox)
        self.R_MagnetOutR_unit.addItem("")
        self.R_MagnetOutR_unit.addItem("")
        self.R_MagnetOutR_unit.addItem("")
        self.R_MagnetOutR_unit.setObjectName(u"R_MagnetOutR_unit")
        self.R_MagnetOutR_unit.setGeometry(QRect(280, 90, 71, 21))
        self.R_MagnetOutR_1 = QDoubleSpinBox(self.groupBox)
        self.R_MagnetOutR_1.setObjectName(u"R_MagnetOutR_1")
        self.R_MagnetOutR_1.setGeometry(QRect(360, 90, 91, 21))
        self.R_MagnetOutR_1.setDecimals(4)
        self.R_MagnetOutR_1.setSingleStep(0.000100000000000)
        self.R_MagnetOutR_1.setValue(0.128200000000000)
        self.R_MagnetBackIronInnerR_2 = QDoubleSpinBox(self.groupBox)
        self.R_MagnetBackIronInnerR_2.setObjectName(u"R_MagnetBackIronInnerR_2")
        self.R_MagnetBackIronInnerR_2.setGeometry(QRect(460, 120, 91, 21))
        self.R_MagnetBackIronInnerR_2.setDecimals(4)
        self.R_MagnetBackIronInnerR_2.setSingleStep(0.000100000000000)
        self.R_MagnetBackIronInnerR_1 = QDoubleSpinBox(self.groupBox)
        self.R_MagnetBackIronInnerR_1.setObjectName(u"R_MagnetBackIronInnerR_1")
        self.R_MagnetBackIronInnerR_1.setGeometry(QRect(360, 120, 91, 21))
        self.R_MagnetBackIronInnerR_1.setDecimals(4)
        self.R_MagnetBackIronInnerR_1.setSingleStep(0.000100000000000)
        self.R_MagnetBackIronInnerR_unit = QComboBox(self.groupBox)
        self.R_MagnetBackIronInnerR_unit.addItem("")
        self.R_MagnetBackIronInnerR_unit.addItem("")
        self.R_MagnetBackIronInnerR_unit.addItem("")
        self.R_MagnetBackIronInnerR_unit.setObjectName(u"R_MagnetBackIronInnerR_unit")
        self.R_MagnetBackIronInnerR_unit.setGeometry(QRect(280, 120, 71, 21))
        self.R_MagneticLossCoef1_2 = QDoubleSpinBox(self.groupBox)
        self.R_MagneticLossCoef1_2.setObjectName(u"R_MagneticLossCoef1_2")
        self.R_MagneticLossCoef1_2.setGeometry(QRect(460, 150, 91, 21))
        self.R_MagneticLossCoef1_2.setDecimals(5)
        self.R_MagneticLossCoef1_2.setSingleStep(0.000100000000000)
        self.R_MagneticLossCoef1_2.setValue(0.001180000000000)
        self.R_MagneticLossCoef1_1 = QDoubleSpinBox(self.groupBox)
        self.R_MagneticLossCoef1_1.setObjectName(u"R_MagneticLossCoef1_1")
        self.R_MagneticLossCoef1_1.setGeometry(QRect(360, 150, 91, 21))
        self.R_MagneticLossCoef1_1.setDecimals(5)
        self.R_MagneticLossCoef1_1.setSingleStep(0.000100000000000)
        self.R_MagneticLossCoef1_1.setValue(0.001180000000000)
        self.R_MagneticLossCoef2_2 = QDoubleSpinBox(self.groupBox)
        self.R_MagneticLossCoef2_2.setObjectName(u"R_MagneticLossCoef2_2")
        self.R_MagneticLossCoef2_2.setGeometry(QRect(460, 180, 91, 21))
        self.R_MagneticLossCoef2_2.setDecimals(5)
        self.R_MagneticLossCoef2_2.setSingleStep(0.000100000000000)
        self.R_MagneticLossCoef2_2.setValue(1.880000000000000)
        self.R_MagneticLossCoef2_1 = QDoubleSpinBox(self.groupBox)
        self.R_MagneticLossCoef2_1.setObjectName(u"R_MagneticLossCoef2_1")
        self.R_MagneticLossCoef2_1.setGeometry(QRect(360, 180, 91, 21))
        self.R_MagneticLossCoef2_1.setDecimals(5)
        self.R_MagneticLossCoef2_1.setSingleStep(0.000100000000000)
        self.R_MagneticLossCoef2_1.setValue(1.880000000000000)
        self.R_MagneticLossCoef3_2 = QDoubleSpinBox(self.groupBox)
        self.R_MagneticLossCoef3_2.setObjectName(u"R_MagneticLossCoef3_2")
        self.R_MagneticLossCoef3_2.setGeometry(QRect(460, 210, 91, 21))
        self.R_MagneticLossCoef3_2.setDecimals(5)
        self.R_MagneticLossCoef3_2.setSingleStep(0.000100000000000)
        self.R_MagneticLossCoef3_2.setValue(1.500000000000000)
        self.R_MagneticLossCoef3_1 = QDoubleSpinBox(self.groupBox)
        self.R_MagneticLossCoef3_1.setObjectName(u"R_MagneticLossCoef3_1")
        self.R_MagneticLossCoef3_1.setGeometry(QRect(360, 210, 91, 21))
        self.R_MagneticLossCoef3_1.setDecimals(5)
        self.R_MagneticLossCoef3_1.setSingleStep(0.000100000000000)
        self.R_MagneticLossCoef3_1.setValue(1.500000000000000)
        self.groupBox_2 = QGroupBox(self.tab_1)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 280, 561, 271))
        self.groupBox_2.setFont(font)
        self.I_NumElecPhase_1 = QSpinBox(self.groupBox_2)
        self.I_NumElecPhase_1.setObjectName(u"I_NumElecPhase_1")
        self.I_NumElecPhase_1.setGeometry(QRect(360, 30, 91, 21))
        self.I_NumElecPhase_1.setValue(3)
        self.R_PhaseCurrentAmp_1 = QDoubleSpinBox(self.groupBox_2)
        self.R_PhaseCurrentAmp_1.setObjectName(u"R_PhaseCurrentAmp_1")
        self.R_PhaseCurrentAmp_1.setGeometry(QRect(360, 60, 91, 21))
        self.R_PhaseCurrentAmp_1.setMaximum(100000.000000000000000)
        self.R_PhaseCurrentAmp_1.setSingleStep(0.000100000000000)
        self.R_PhaseCurrentAmp_1.setValue(9000.000000000000000)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 30, 181, 21))
        self.I_NumElecPhase_2 = QSpinBox(self.groupBox_2)
        self.I_NumElecPhase_2.setObjectName(u"I_NumElecPhase_2")
        self.I_NumElecPhase_2.setGeometry(QRect(460, 30, 91, 21))
        self.I_NumElecPhase_2.setValue(3)
        self.R_PhaseCurrentAmp_unit = QComboBox(self.groupBox_2)
        self.R_PhaseCurrentAmp_unit.addItem("")
        self.R_PhaseCurrentAmp_unit.setObjectName(u"R_PhaseCurrentAmp_unit")
        self.R_PhaseCurrentAmp_unit.setGeometry(QRect(280, 60, 71, 21))
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 60, 241, 21))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 90, 151, 21))
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 120, 231, 21))
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 150, 151, 21))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 180, 251, 21))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 210, 151, 21))
        self.R_PhaseCurrentAmp_2 = QDoubleSpinBox(self.groupBox_2)
        self.R_PhaseCurrentAmp_2.setObjectName(u"R_PhaseCurrentAmp_2")
        self.R_PhaseCurrentAmp_2.setGeometry(QRect(460, 60, 91, 21))
        self.R_PhaseCurrentAmp_2.setMaximum(100000.000000000000000)
        self.R_PhaseCurrentAmp_2.setSingleStep(0.000100000000000)
        self.R_PhaseCurrentAmp_2.setValue(9000.000000000000000)
        self.R_WireCopperR_2 = QDoubleSpinBox(self.groupBox_2)
        self.R_WireCopperR_2.setObjectName(u"R_WireCopperR_2")
        self.R_WireCopperR_2.setGeometry(QRect(460, 90, 91, 21))
        self.R_WireCopperR_2.setDecimals(6)
        self.R_WireCopperR_2.setSingleStep(0.000100000000000)
        self.R_WireCopperR_2.setValue(0.012700000000000)
        self.R_WireCopperR_unit = QComboBox(self.groupBox_2)
        self.R_WireCopperR_unit.addItem("")
        self.R_WireCopperR_unit.addItem("")
        self.R_WireCopperR_unit.addItem("")
        self.R_WireCopperR_unit.setObjectName(u"R_WireCopperR_unit")
        self.R_WireCopperR_unit.setGeometry(QRect(280, 90, 71, 21))
        self.R_WireCopperR_1 = QDoubleSpinBox(self.groupBox_2)
        self.R_WireCopperR_1.setObjectName(u"R_WireCopperR_1")
        self.R_WireCopperR_1.setGeometry(QRect(360, 90, 91, 21))
        self.R_WireCopperR_1.setDecimals(6)
        self.R_WireCopperR_1.setSingleStep(0.000100000000000)
        self.R_WireCopperR_1.setValue(0.012700000000000)
        self.R_InsulThick_2 = QDoubleSpinBox(self.groupBox_2)
        self.R_InsulThick_2.setObjectName(u"R_InsulThick_2")
        self.R_InsulThick_2.setGeometry(QRect(460, 120, 91, 21))
        self.R_InsulThick_2.setDecimals(6)
        self.R_InsulThick_2.setSingleStep(0.000100000000000)
        self.R_InsulThick_1 = QDoubleSpinBox(self.groupBox_2)
        self.R_InsulThick_1.setObjectName(u"R_InsulThick_1")
        self.R_InsulThick_1.setGeometry(QRect(360, 120, 91, 21))
        self.R_InsulThick_1.setDecimals(6)
        self.R_InsulThick_1.setSingleStep(0.000100000000000)
        self.R_InsulThick_unit = QComboBox(self.groupBox_2)
        self.R_InsulThick_unit.addItem("")
        self.R_InsulThick_unit.addItem("")
        self.R_InsulThick_unit.addItem("")
        self.R_InsulThick_unit.setObjectName(u"R_InsulThick_unit")
        self.R_InsulThick_unit.setGeometry(QRect(280, 120, 71, 21))
        self.R_FillFactor_2 = QDoubleSpinBox(self.groupBox_2)
        self.R_FillFactor_2.setObjectName(u"R_FillFactor_2")
        self.R_FillFactor_2.setGeometry(QRect(460, 150, 91, 21))
        self.R_FillFactor_2.setSingleStep(0.010000000000000)
        self.R_FillFactor_2.setValue(0.590000000000000)
        self.R_FillFactor_1 = QDoubleSpinBox(self.groupBox_2)
        self.R_FillFactor_1.setObjectName(u"R_FillFactor_1")
        self.R_FillFactor_1.setGeometry(QRect(360, 150, 91, 21))
        self.R_FillFactor_1.setSingleStep(0.010000000000000)
        self.R_FillFactor_1.setValue(0.590000000000000)
        self.R_LaminatToothWedgeThickness_2 = QDoubleSpinBox(self.groupBox_2)
        self.R_LaminatToothWedgeThickness_2.setObjectName(u"R_LaminatToothWedgeThickness_2")
        self.R_LaminatToothWedgeThickness_2.setGeometry(QRect(460, 180, 91, 21))
        self.R_LaminatToothWedgeThickness_2.setDecimals(6)
        self.R_LaminatToothWedgeThickness_2.setSingleStep(0.000100000000000)
        self.R_LaminatToothWedgeThickness_2.setValue(0.007000000000000)
        self.R_LaminatToothWedgeThickness_1 = QDoubleSpinBox(self.groupBox_2)
        self.R_LaminatToothWedgeThickness_1.setObjectName(u"R_LaminatToothWedgeThickness_1")
        self.R_LaminatToothWedgeThickness_1.setGeometry(QRect(360, 180, 91, 21))
        self.R_LaminatToothWedgeThickness_1.setDecimals(6)
        self.R_LaminatToothWedgeThickness_1.setSingleStep(0.000100000000000)
        self.R_LaminatToothWedgeThickness_1.setValue(0.007000000000000)
        self.R_LaminatR_2 = QDoubleSpinBox(self.groupBox_2)
        self.R_LaminatR_2.setObjectName(u"R_LaminatR_2")
        self.R_LaminatR_2.setGeometry(QRect(460, 210, 91, 21))
        self.R_LaminatR_2.setDecimals(6)
        self.R_LaminatR_2.setSingleStep(0.000100000000000)
        self.R_LaminatR_2.setValue(0.256300000000000)
        self.R_LaminatR_1 = QDoubleSpinBox(self.groupBox_2)
        self.R_LaminatR_1.setObjectName(u"R_LaminatR_1")
        self.R_LaminatR_1.setGeometry(QRect(360, 210, 91, 21))
        self.R_LaminatR_1.setDecimals(6)
        self.R_LaminatR_1.setSingleStep(0.000100000000000)
        self.R_LaminatR_1.setValue(0.256300000000000)
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 240, 191, 21))
        self.R_LaminatToothWedgeThickness_unit = QComboBox(self.groupBox_2)
        self.R_LaminatToothWedgeThickness_unit.addItem("")
        self.R_LaminatToothWedgeThickness_unit.addItem("")
        self.R_LaminatToothWedgeThickness_unit.addItem("")
        self.R_LaminatToothWedgeThickness_unit.setObjectName(u"R_LaminatToothWedgeThickness_unit")
        self.R_LaminatToothWedgeThickness_unit.setGeometry(QRect(280, 180, 71, 21))
        self.R_LaminatR_unit = QComboBox(self.groupBox_2)
        self.R_LaminatR_unit.addItem("")
        self.R_LaminatR_unit.addItem("")
        self.R_LaminatR_unit.addItem("")
        self.R_LaminatR_unit.setObjectName(u"R_LaminatR_unit")
        self.R_LaminatR_unit.setGeometry(QRect(280, 210, 71, 21))
        self.R_LamSlotLinerThick_2 = QDoubleSpinBox(self.groupBox_2)
        self.R_LamSlotLinerThick_2.setObjectName(u"R_LamSlotLinerThick_2")
        self.R_LamSlotLinerThick_2.setGeometry(QRect(460, 240, 91, 21))
        self.R_LamSlotLinerThick_2.setDecimals(6)
        self.R_LamSlotLinerThick_2.setSingleStep(0.000100000000000)
        self.R_LamSlotLinerThick_2.setValue(0.000254000000000)
        self.R_LamSlotLinerThick_1 = QDoubleSpinBox(self.groupBox_2)
        self.R_LamSlotLinerThick_1.setObjectName(u"R_LamSlotLinerThick_1")
        self.R_LamSlotLinerThick_1.setGeometry(QRect(360, 240, 91, 21))
        self.R_LamSlotLinerThick_1.setDecimals(6)
        self.R_LamSlotLinerThick_1.setSingleStep(0.000100000000000)
        self.R_LamSlotLinerThick_1.setValue(0.000254000000000)
        self.R_LamSlotLinerThick_unit = QComboBox(self.groupBox_2)
        self.R_LamSlotLinerThick_unit.addItem("")
        self.R_LamSlotLinerThick_unit.addItem("")
        self.R_LamSlotLinerThick_unit.addItem("")
        self.R_LamSlotLinerThick_unit.setObjectName(u"R_LamSlotLinerThick_unit")
        self.R_LamSlotLinerThick_unit.setGeometry(QRect(280, 240, 71, 21))
        self.groupBox_4 = QGroupBox(self.tab_1)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(610, 230, 501, 121))
        self.groupBox_4.setFont(font)
        self.R_LoadInertia_1 = QDoubleSpinBox(self.groupBox_4)
        self.R_LoadInertia_1.setObjectName(u"R_LoadInertia_1")
        self.R_LoadInertia_1.setGeometry(QRect(300, 60, 91, 21))
        self.R_LoadInertia_1.setDecimals(5)
        self.R_LoadInertia_1.setSingleStep(0.000100000000000)
        self.label_31 = QLabel(self.groupBox_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 30, 151, 21))
        self.R_LoadInertia_unit = QComboBox(self.groupBox_4)
        self.R_LoadInertia_unit.addItem("")
        self.R_LoadInertia_unit.addItem("")
        self.R_LoadInertia_unit.setObjectName(u"R_LoadInertia_unit")
        self.R_LoadInertia_unit.setGeometry(QRect(210, 60, 81, 21))
        self.label_32 = QLabel(self.groupBox_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 60, 231, 21))
        self.label_33 = QLabel(self.groupBox_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 90, 151, 21))
        self.R_LoadInertia_2 = QDoubleSpinBox(self.groupBox_4)
        self.R_LoadInertia_2.setObjectName(u"R_LoadInertia_2")
        self.R_LoadInertia_2.setGeometry(QRect(400, 60, 91, 21))
        self.R_LoadInertia_2.setDecimals(5)
        self.R_LoadInertia_2.setSingleStep(0.000100000000000)
        self.R_GearRatio_2 = QDoubleSpinBox(self.groupBox_4)
        self.R_GearRatio_2.setObjectName(u"R_GearRatio_2")
        self.R_GearRatio_2.setGeometry(QRect(400, 90, 91, 21))
        self.R_GearRatio_2.setValue(15.000000000000000)
        self.R_MtrLength_unit = QComboBox(self.groupBox_4)
        self.R_MtrLength_unit.addItem("")
        self.R_MtrLength_unit.addItem("")
        self.R_MtrLength_unit.addItem("")
        self.R_MtrLength_unit.setObjectName(u"R_MtrLength_unit")
        self.R_MtrLength_unit.setGeometry(QRect(210, 30, 81, 21))
        self.R_GearRatio_1 = QDoubleSpinBox(self.groupBox_4)
        self.R_GearRatio_1.setObjectName(u"R_GearRatio_1")
        self.R_GearRatio_1.setGeometry(QRect(300, 90, 91, 21))
        self.R_GearRatio_1.setValue(15.000000000000000)
        self.R_MtrLength_1 = QDoubleSpinBox(self.groupBox_4)
        self.R_MtrLength_1.setObjectName(u"R_MtrLength_1")
        self.R_MtrLength_1.setGeometry(QRect(300, 30, 91, 21))
        self.R_MtrLength_1.setDecimals(5)
        self.R_MtrLength_1.setSingleStep(0.000100000000000)
        self.R_MtrLength_1.setValue(0.509800000000000)
        self.R_MtrLength_2 = QDoubleSpinBox(self.groupBox_4)
        self.R_MtrLength_2.setObjectName(u"R_MtrLength_2")
        self.R_MtrLength_2.setGeometry(QRect(400, 30, 91, 21))
        self.R_MtrLength_2.setDecimals(5)
        self.R_MtrLength_2.setSingleStep(0.000100000000000)
        self.R_MtrLength_2.setValue(0.509800000000000)
        self.groupBox_17 = QGroupBox(self.tab_1)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(610, 20, 501, 151))
        self.groupBox_17.setFont(font)
        self.R_FluidSpecificGrav_1 = QDoubleSpinBox(self.groupBox_17)
        self.R_FluidSpecificGrav_1.setObjectName(u"R_FluidSpecificGrav_1")
        self.R_FluidSpecificGrav_1.setGeometry(QRect(300, 60, 91, 21))
        self.R_FluidSpecificGrav_1.setDecimals(5)
        self.R_FluidSpecificGrav_1.setSingleStep(0.000100000000000)
        self.R_FluidSpecificGrav_1.setValue(0.001000000000000)
        self.label_34 = QLabel(self.groupBox_17)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 30, 151, 21))
        self.R_FluidKinVisc_unit = QComboBox(self.groupBox_17)
        self.R_FluidKinVisc_unit.addItem("")
        self.R_FluidKinVisc_unit.setObjectName(u"R_FluidKinVisc_unit")
        self.R_FluidKinVisc_unit.setGeometry(QRect(210, 90, 81, 21))
        self.label_35 = QLabel(self.groupBox_17)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 60, 231, 21))
        self.label_36 = QLabel(self.groupBox_17)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 90, 151, 21))
        self.R_FluidSpecificGrav_2 = QDoubleSpinBox(self.groupBox_17)
        self.R_FluidSpecificGrav_2.setObjectName(u"R_FluidSpecificGrav_2")
        self.R_FluidSpecificGrav_2.setGeometry(QRect(400, 60, 91, 21))
        self.R_FluidSpecificGrav_2.setDecimals(5)
        self.R_FluidSpecificGrav_2.setSingleStep(0.000100000000000)
        self.R_FluidSpecificGrav_2.setValue(0.001000000000000)
        self.R_FluidKinVisc_2 = QDoubleSpinBox(self.groupBox_17)
        self.R_FluidKinVisc_2.setObjectName(u"R_FluidKinVisc_2")
        self.R_FluidKinVisc_2.setGeometry(QRect(400, 90, 91, 21))
        self.R_FluidKinVisc_2.setValue(15.000000000000000)
        self.R_AirgapRadialLength_unit = QComboBox(self.groupBox_17)
        self.R_AirgapRadialLength_unit.addItem("")
        self.R_AirgapRadialLength_unit.addItem("")
        self.R_AirgapRadialLength_unit.addItem("")
        self.R_AirgapRadialLength_unit.setObjectName(u"R_AirgapRadialLength_unit")
        self.R_AirgapRadialLength_unit.setGeometry(QRect(210, 30, 81, 21))
        self.R_FluidKinVisc_1 = QDoubleSpinBox(self.groupBox_17)
        self.R_FluidKinVisc_1.setObjectName(u"R_FluidKinVisc_1")
        self.R_FluidKinVisc_1.setGeometry(QRect(300, 90, 91, 21))
        self.R_FluidKinVisc_1.setValue(15.000000000000000)
        self.R_AirgapRadialLength_1 = QDoubleSpinBox(self.groupBox_17)
        self.R_AirgapRadialLength_1.setObjectName(u"R_AirgapRadialLength_1")
        self.R_AirgapRadialLength_1.setGeometry(QRect(300, 30, 91, 21))
        self.R_AirgapRadialLength_1.setDecimals(6)
        self.R_AirgapRadialLength_1.setSingleStep(0.000100000000000)
        self.R_AirgapRadialLength_1.setValue(0.000635000000000)
        self.R_AirgapRadialLength_2 = QDoubleSpinBox(self.groupBox_17)
        self.R_AirgapRadialLength_2.setObjectName(u"R_AirgapRadialLength_2")
        self.R_AirgapRadialLength_2.setGeometry(QRect(400, 30, 91, 21))
        self.R_AirgapRadialLength_2.setDecimals(6)
        self.R_AirgapRadialLength_2.setSingleStep(0.000100000000000)
        self.R_AirgapRadialLength_2.setValue(0.000635000000000)
        self.R_VacMagneticPerm_2 = QDoubleSpinBox(self.groupBox_17)
        self.R_VacMagneticPerm_2.setObjectName(u"R_VacMagneticPerm_2")
        self.R_VacMagneticPerm_2.setGeometry(QRect(400, 120, 91, 21))
        self.R_VacMagneticPerm_2.setDecimals(6)
        self.R_VacMagneticPerm_2.setSingleStep(0.000100000000000)
        self.R_VacMagneticPerm_2.setValue(0.000001000000000)
        self.R_VacMagneticPerm_1 = QDoubleSpinBox(self.groupBox_17)
        self.R_VacMagneticPerm_1.setObjectName(u"R_VacMagneticPerm_1")
        self.R_VacMagneticPerm_1.setGeometry(QRect(300, 120, 91, 21))
        self.R_VacMagneticPerm_1.setDecimals(6)
        self.R_VacMagneticPerm_1.setSingleStep(0.000100000000000)
        self.R_VacMagneticPerm_1.setValue(0.000001000000000)
        self.label_39 = QLabel(self.groupBox_17)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 120, 231, 21))
        self.R_VacMagneticPerm_unit = QComboBox(self.groupBox_17)
        self.R_VacMagneticPerm_unit.addItem("")
        self.R_VacMagneticPerm_unit.setObjectName(u"R_VacMagneticPerm_unit")
        self.R_VacMagneticPerm_unit.setGeometry(QRect(210, 120, 81, 21))
        self.groupBox_18 = QGroupBox(self.tab_1)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(610, 420, 501, 131))
        self.groupBox_18.setFont(font)
        self.label_40 = QLabel(self.groupBox_18)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 30, 151, 21))
        self.label_41 = QLabel(self.groupBox_18)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 60, 231, 21))
        self.label_42 = QLabel(self.groupBox_18)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 90, 151, 21))
        self.Magnet_Material = QComboBox(self.groupBox_18)
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.addItem("")
        self.Magnet_Material.setObjectName(u"Magnet_Material")
        self.Magnet_Material.setGeometry(QRect(210, 30, 271, 21))
        self.Iron_Material = QComboBox(self.groupBox_18)
        self.Iron_Material.addItem("")
        self.Iron_Material.addItem("")
        self.Iron_Material.addItem("")
        self.Iron_Material.addItem("")
        self.Iron_Material.addItem("")
        self.Iron_Material.addItem("")
        self.Iron_Material.addItem("")
        self.Iron_Material.setObjectName(u"Iron_Material")
        self.Iron_Material.setGeometry(QRect(210, 60, 271, 21))
        self.Lamination_Material = QComboBox(self.groupBox_18)
        self.Lamination_Material.addItem("")
        self.Lamination_Material.addItem("")
        self.Lamination_Material.setObjectName(u"Lamination_Material")
        self.Lamination_Material.setGeometry(QRect(210, 90, 271, 21))
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_19 = QGroupBox(self.tab_2)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(540, 230, 341, 201))
        self.groupBox_19.setFont(font)
        self.label_44 = QLabel(self.groupBox_19)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 30, 151, 21))
        self.label_45 = QLabel(self.groupBox_19)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 60, 231, 21))
        self.label_46 = QLabel(self.groupBox_19)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 90, 151, 21))
        self.R_MagneticLossCoef3_13 = QDoubleSpinBox(self.groupBox_19)
        self.R_MagneticLossCoef3_13.setObjectName(u"R_MagneticLossCoef3_13")
        self.R_MagneticLossCoef3_13.setGeometry(QRect(460, 210, 91, 21))
        self.DisMut = QDoubleSpinBox(self.groupBox_19)
        self.DisMut.setObjectName(u"DisMut")
        self.DisMut.setGeometry(QRect(230, 120, 91, 21))
        self.DisMut.setValue(5.000000000000000)
        self.label_48 = QLabel(self.groupBox_19)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(10, 120, 231, 21))
        self.label_49 = QLabel(self.groupBox_19)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 150, 231, 21))
        self.ProbMut = QDoubleSpinBox(self.groupBox_19)
        self.ProbMut.setObjectName(u"ProbMut")
        self.ProbMut.setGeometry(QRect(230, 150, 91, 21))
        self.ProbMut.setSingleStep(0.010000000000000)
        self.ProbMut.setValue(0.100000000000000)
        self.npop = QSpinBox(self.groupBox_19)
        self.npop.setObjectName(u"npop")
        self.npop.setGeometry(QRect(230, 30, 91, 21))
        self.npop.setMaximum(10000)
        self.npop.setValue(10)
        self.ngens = QSpinBox(self.groupBox_19)
        self.ngens.setObjectName(u"ngens")
        self.ngens.setGeometry(QRect(230, 60, 91, 21))
        self.ngens.setMaximum(10000)
        self.ngens.setValue(10)
        self.nprocesses = QSpinBox(self.groupBox_19)
        self.nprocesses.setObjectName(u"nprocesses")
        self.nprocesses.setGeometry(QRect(230, 90, 91, 21))
        self.nprocesses.setMaximum(20)
        self.nprocesses.setValue(2)
        self.groupBox_20 = QGroupBox(self.tab_2)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setGeometry(QRect(0, 20, 881, 201))
        self.groupBox_20.setFont(font)
        self.label_50 = QLabel(self.groupBox_20)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(10, 30, 291, 21))
        self.label_51 = QLabel(self.groupBox_20)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 60, 351, 21))
        self.label_52 = QLabel(self.groupBox_20)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(10, 90, 231, 21))
        self.MinEff_ = QDoubleSpinBox(self.groupBox_20)
        self.MinEff_.setObjectName(u"MinEff_")
        self.MinEff_.setGeometry(QRect(470, 90, 91, 21))
        self.MinEff_.setSingleStep(0.050000000000000)
        self.MinEff_.setValue(0.500000000000000)
        self.MaxWeight = QDoubleSpinBox(self.groupBox_20)
        self.MaxWeight.setObjectName(u"MaxWeight")
        self.MaxWeight.setGeometry(QRect(470, 120, 91, 21))
        self.MaxWeight.setMaximum(20000.000000000000000)
        self.MaxWeight.setValue(1000.000000000000000)
        self.label_54 = QLabel(self.groupBox_20)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(10, 120, 231, 21))
        self.label_55 = QLabel(self.groupBox_20)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(10, 150, 231, 21))
        self.VDC = QDoubleSpinBox(self.groupBox_20)
        self.VDC.setObjectName(u"VDC")
        self.VDC.setGeometry(QRect(470, 150, 91, 21))
        self.VDC.setMaximum(2000.000000000000000)
        self.VDC.setValue(1000.000000000000000)
        self.SpeedReq = QLineEdit(self.groupBox_20)
        self.SpeedReq.setObjectName(u"SpeedReq")
        self.SpeedReq.setGeometry(QRect(470, 30, 401, 21))
        self.SpeedReq.setFocusPolicy(Qt.StrongFocus)
        self.MinTor = QLineEdit(self.groupBox_20)
        self.MinTor.setObjectName(u"MinTor")
        self.MinTor.setGeometry(QRect(470, 60, 401, 21))
        self.SpeedReq_unit = QComboBox(self.groupBox_20)
        self.SpeedReq_unit.addItem("")
        self.SpeedReq_unit.addItem("")
        self.SpeedReq_unit.addItem("")
        self.SpeedReq_unit.setObjectName(u"SpeedReq_unit")
        self.SpeedReq_unit.setGeometry(QRect(380, 30, 71, 21))
        self.MinTor_unit = QComboBox(self.groupBox_20)
        self.MinTor_unit.addItem("")
        self.MinTor_unit.addItem("")
        self.MinTor_unit.addItem("")
        self.MinTor_unit.setObjectName(u"MinTor_unit")
        self.MinTor_unit.setGeometry(QRect(380, 60, 71, 21))
        self.MinEff_unit = QComboBox(self.groupBox_20)
        self.MinEff_unit.addItem("")
        self.MinEff_unit.setObjectName(u"MinEff_unit")
        self.MinEff_unit.setGeometry(QRect(380, 90, 71, 21))
        self.MaxWeigh_unit = QComboBox(self.groupBox_20)
        self.MaxWeigh_unit.addItem("")
        self.MaxWeigh_unit.addItem("")
        self.MaxWeigh_unit.setObjectName(u"MaxWeigh_unit")
        self.MaxWeigh_unit.setGeometry(QRect(380, 120, 71, 21))
        self.VDC_unit = QComboBox(self.groupBox_20)
        self.VDC_unit.addItem("")
        self.VDC_unit.setObjectName(u"VDC_unit")
        self.VDC_unit.setGeometry(QRect(380, 150, 71, 21))
        self.groupBox_21 = QGroupBox(self.tab_2)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(0, 230, 431, 271))
        self.groupBox_21.setFont(font)
        self.R_MagneticLossCoef3_17 = QDoubleSpinBox(self.groupBox_21)
        self.R_MagneticLossCoef3_17.setObjectName(u"R_MagneticLossCoef3_17")
        self.R_MagneticLossCoef3_17.setGeometry(QRect(460, 210, 91, 21))
        self.TorqueOpt = QCheckBox(self.groupBox_21)
        self.TorqueOpt.setObjectName(u"TorqueOpt")
        self.TorqueOpt.setEnabled(True)
        self.TorqueOpt.setGeometry(QRect(10, 30, 351, 24))
        self.TorqueOpt.setCheckable(True)
        self.TorqueOpt.setChecked(False)
        self.TorqueOpt.setTristate(False)
        self.EfficinecyOpt_min = QCheckBox(self.groupBox_21)
        self.EfficinecyOpt_min.setObjectName(u"EfficinecyOpt_min")
        self.EfficinecyOpt_min.setGeometry(QRect(10, 60, 351, 24))
        self.EfficinecyOpt_max = QCheckBox(self.groupBox_21)
        self.EfficinecyOpt_max.setObjectName(u"EfficinecyOpt_max")
        self.EfficinecyOpt_max.setGeometry(QRect(10, 90, 351, 24))
        self.WeightOpt = QCheckBox(self.groupBox_21)
        self.WeightOpt.setObjectName(u"WeightOpt")
        self.WeightOpt.setGeometry(QRect(10, 120, 351, 24))
        self.MagWeightOpt = QCheckBox(self.groupBox_21)
        self.MagWeightOpt.setObjectName(u"MagWeightOpt")
        self.MagWeightOpt.setGeometry(QRect(10, 150, 351, 24))
        self.VoltageOpt = QCheckBox(self.groupBox_21)
        self.VoltageOpt.setObjectName(u"VoltageOpt")
        self.VoltageOpt.setGeometry(QRect(10, 180, 351, 24))
        self.MtrLengthOpt = QCheckBox(self.groupBox_21)
        self.MtrLengthOpt.setObjectName(u"MtrLengthOpt")
        self.MtrLengthOpt.setGeometry(QRect(10, 210, 351, 24))
        self.MtrRadiusOpt = QCheckBox(self.groupBox_21)
        self.MtrRadiusOpt.setObjectName(u"MtrRadiusOpt")
        self.MtrRadiusOpt.setGeometry(QRect(10, 240, 351, 24))
        self.Execution = QPushButton(self.tab_2)
        self.Execution.setObjectName(u"Execution")
        self.Execution.setGeometry(QRect(540, 450, 341, 31))
        palette = QPalette()
        brush = QBrush(QColor(85, 255, 127, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush1 = QBrush(QColor(240, 240, 240, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.Execution.setPalette(palette)
        self.Execution.setAutoDefault(False)
        self.Execution.setFlat(False)
        self.progressBar = QProgressBar(self.tab_2)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(540, 490, 341, 23))
        self.progressBar.setLayoutDirection(Qt.LeftToRight)
        self.progressBar.setValue(0)
        self.progressBar.setAlignment(Qt.AlignCenter)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_22 = QGroupBox(self.tab_3)
        self.groupBox_22.setObjectName(u"groupBox_22")
        self.groupBox_22.setGeometry(QRect(30, 10, 291, 531))
        self.groupBox_22.setFont(font)
        self.R_MagneticLossCoef3_18 = QDoubleSpinBox(self.groupBox_22)
        self.R_MagneticLossCoef3_18.setObjectName(u"R_MagneticLossCoef3_18")
        self.R_MagneticLossCoef3_18.setGeometry(QRect(460, 210, 91, 21))
        self.MinTrqMargin_Percent = QCheckBox(self.groupBox_22)
        self.MinTrqMargin_Percent.setObjectName(u"MinTrqMargin_Percent")
        self.MinTrqMargin_Percent.setGeometry(QRect(10, 30, 351, 24))
        self.MeanTrqMargin_Percent = QCheckBox(self.groupBox_22)
        self.MeanTrqMargin_Percent.setObjectName(u"MeanTrqMargin_Percent")
        self.MeanTrqMargin_Percent.setGeometry(QRect(10, 60, 351, 24))
        self.MinEffMtr_Percent = QCheckBox(self.groupBox_22)
        self.MinEffMtr_Percent.setObjectName(u"MinEffMtr_Percent")
        self.MinEffMtr_Percent.setGeometry(QRect(10, 90, 351, 24))
        self.MeanEffMtr_Percent = QCheckBox(self.groupBox_22)
        self.MeanEffMtr_Percent.setObjectName(u"MeanEffMtr_Percent")
        self.MeanEffMtr_Percent.setGeometry(QRect(10, 120, 351, 24))
        self.Weight_kg = QCheckBox(self.groupBox_22)
        self.Weight_kg.setObjectName(u"Weight_kg")
        self.Weight_kg.setGeometry(QRect(10, 150, 351, 24))
        self.VDC_2 = QCheckBox(self.groupBox_22)
        self.VDC_2.setObjectName(u"VDC_2")
        self.VDC_2.setGeometry(QRect(10, 180, 351, 24))
        self.MagVol_m3 = QCheckBox(self.groupBox_22)
        self.MagVol_m3.setObjectName(u"MagVol_m3")
        self.MagVol_m3.setGeometry(QRect(10, 210, 351, 24))
        self.R_MtrLength_m = QCheckBox(self.groupBox_22)
        self.R_MtrLength_m.setObjectName(u"R_MtrLength_m")
        self.R_MtrLength_m.setGeometry(QRect(10, 240, 351, 24))
        self.R_LaminatR_m = QCheckBox(self.groupBox_22)
        self.R_LaminatR_m.setObjectName(u"R_LaminatR_m")
        self.R_LaminatR_m.setGeometry(QRect(10, 270, 351, 24))
        self.MaxTotalLoss_W = QCheckBox(self.groupBox_22)
        self.MaxTotalLoss_W.setObjectName(u"MaxTotalLoss_W")
        self.MaxTotalLoss_W.setGeometry(QRect(10, 300, 351, 24))
        self.dropdown1 = QComboBox(self.groupBox_22)
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.addItem("")
        self.dropdown1.setObjectName(u"dropdown1")
        self.dropdown1.setGeometry(QRect(10, 350, 271, 21))
        self.dropdown2 = QComboBox(self.groupBox_22)
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.addItem("")
        self.dropdown2.setObjectName(u"dropdown2")
        self.dropdown2.setGeometry(QRect(10, 380, 271, 21))
        self.dropdown3 = QComboBox(self.groupBox_22)
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.addItem("")
        self.dropdown3.setObjectName(u"dropdown3")
        self.dropdown3.setGeometry(QRect(10, 410, 271, 21))
        self.ParallelPlot = QPushButton(self.groupBox_22)
        self.ParallelPlot.setObjectName(u"ParallelPlot")
        self.ParallelPlot.setGeometry(QRect(40, 480, 89, 28))
        self.ThreeDPlot = QPushButton(self.groupBox_22)
        self.ThreeDPlot.setObjectName(u"ThreeDPlot")
        self.ThreeDPlot.setGeometry(QRect(160, 480, 89, 28))
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1145, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Rotor", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Number of Pole Pairs", None))
        self.R_MagnetRadialLength_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_MagnetRadialLength_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_MagnetRadialLength_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Radial Length of Magnet", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Magnet Outer Radius", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Magnet Assembly Backiron Inner Radius", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Magnetic Loss Coeff, a1", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Magnetic Loss Coeff, a2", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Magnetic Loss Coeff, a3", None))
        self.R_MagnetOutR_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_MagnetOutR_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_MagnetOutR_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.R_MagnetBackIronInnerR_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_MagnetBackIronInnerR_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_MagnetBackIronInnerR_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Stator", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Number of Electrical Phase", None))
        self.R_PhaseCurrentAmp_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Apk", None))

        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Phase Current Amplitude at Max. Torque", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Wire Copper Radius", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Wire Insulation Thickness", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Fill Factor", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Lamination Tooth Tip and Wedge Thickness", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Lamination Outer Radius", None))
        self.R_WireCopperR_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_WireCopperR_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_WireCopperR_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.R_InsulThick_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_InsulThick_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_InsulThick_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Lamination Slot Liner Thickness", None))
        self.R_LaminatToothWedgeThickness_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_LaminatToothWedgeThickness_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_LaminatToothWedgeThickness_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.R_LaminatR_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_LaminatR_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_LaminatR_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.R_LamSlotLinerThick_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_LamSlotLinerThick_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_LamSlotLinerThick_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Mechanical", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Motor Length", None))
        self.R_LoadInertia_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"kg.m/s^2", None))
        self.R_LoadInertia_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"oz.in/s^2", None))

        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Load Inertia Reflected to Motor", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Gear Ratio", None))
        self.R_MtrLength_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_MtrLength_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_MtrLength_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.groupBox_17.setTitle(QCoreApplication.translate("MainWindow", u"Airgap", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Airgap Distance", None))
        self.R_FluidKinVisc_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"cSt", None))

        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Airgap Fluid Specific Gravity", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Airgap Fluid Viscosity", None))
        self.R_AirgapRadialLength_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Meter", None))
        self.R_AirgapRadialLength_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"Millimeter", None))
        self.R_AirgapRadialLength_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Inch", None))

        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Magnetic Perm of Vacuum", None))
        self.R_VacMagneticPerm_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"H/m", None))

        self.groupBox_18.setTitle(QCoreApplication.translate("MainWindow", u"Material", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Magnet Material", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Iron Material", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Lamination Material", None))
        self.Magnet_Material.setItemText(0, QCoreApplication.translate("MainWindow", u"Recoma 18", None))
        self.Magnet_Material.setItemText(1, QCoreApplication.translate("MainWindow", u"Recoma 20", None))
        self.Magnet_Material.setItemText(2, QCoreApplication.translate("MainWindow", u"Recoma 22", None))
        self.Magnet_Material.setItemText(3, QCoreApplication.translate("MainWindow", u"Recoma 25", None))
        self.Magnet_Material.setItemText(4, QCoreApplication.translate("MainWindow", u"Recoma 24HE", None))
        self.Magnet_Material.setItemText(5, QCoreApplication.translate("MainWindow", u"Recoma 26", None))
        self.Magnet_Material.setItemText(6, QCoreApplication.translate("MainWindow", u"Recoma 26HE", None))
        self.Magnet_Material.setItemText(7, QCoreApplication.translate("MainWindow", u"Recoma 28", None))
        self.Magnet_Material.setItemText(8, QCoreApplication.translate("MainWindow", u"Recoma 28HE", None))
        self.Magnet_Material.setItemText(9, QCoreApplication.translate("MainWindow", u"Recoma 30", None))
        self.Magnet_Material.setItemText(10, QCoreApplication.translate("MainWindow", u"Recoma 30HE", None))
        self.Magnet_Material.setItemText(11, QCoreApplication.translate("MainWindow", u"Recoma 30S", None))
        self.Magnet_Material.setItemText(12, QCoreApplication.translate("MainWindow", u"Recoma 32", None))
        self.Magnet_Material.setItemText(13, QCoreApplication.translate("MainWindow", u"Recoma 32S", None))
        self.Magnet_Material.setItemText(14, QCoreApplication.translate("MainWindow", u"Recoma 33E", None))
        self.Magnet_Material.setItemText(15, QCoreApplication.translate("MainWindow", u"Recoma 35E", None))

        self.Iron_Material.setItemText(0, QCoreApplication.translate("MainWindow", u"M19", None))
        self.Iron_Material.setItemText(1, QCoreApplication.translate("MainWindow", u"430 Stainless Steel", None))
        self.Iron_Material.setItemText(2, QCoreApplication.translate("MainWindow", u"1215 Steel", None))
        self.Iron_Material.setItemText(3, QCoreApplication.translate("MainWindow", u"1018 Steel", None))
        self.Iron_Material.setItemText(4, QCoreApplication.translate("MainWindow", u"1008 Steel", None))
        self.Iron_Material.setItemText(5, QCoreApplication.translate("MainWindow", u"1010 Steel", None))
        self.Iron_Material.setItemText(6, QCoreApplication.translate("MainWindow", u"Hiperco 50", None))

        self.Lamination_Material.setItemText(0, QCoreApplication.translate("MainWindow", u"M19", None))
        self.Lamination_Material.setItemText(1, QCoreApplication.translate("MainWindow", u"Hiperco 50", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Motor Parameters", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("MainWindow", u"Optimizer Configuration", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Population size", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Number of generations", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Number of processors", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Distribution of mutation", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Probability of mutation", None))
        self.groupBox_20.setTitle(QCoreApplication.translate("MainWindow", u"Performance Requirements", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Comma-Separated Gearbox Output Speed Points", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Comma-Separated Gearbox Output Min. Torque Points", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Minimum Acceptable Motor Efficiency", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Maximum Acceptable Motor Weight", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Minimum Available Bus Voltage", None))
        self.SpeedReq.setInputMask("")
        self.SpeedReq.setText(QCoreApplication.translate("MainWindow", u"30.0, 562.0, 706.0, 417.0", None))
        self.MinTor.setText(QCoreApplication.translate("MainWindow", u"51079.0, 4000.0, 11782.0, 25261.0", None))
        self.SpeedReq_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"rpm", None))
        self.SpeedReq_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"rad/s", None))
        self.SpeedReq_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"Hz", None))

        self.MinTor_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Nm", None))
        self.MinTor_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"in.lb", None))
        self.MinTor_unit.setItemText(2, QCoreApplication.translate("MainWindow", u"ft.lb", None))

        self.MinEff_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"Fraction", None))

        self.MaxWeigh_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"kg", None))
        self.MaxWeigh_unit.setItemText(1, QCoreApplication.translate("MainWindow", u"lbm", None))

        self.VDC_unit.setItemText(0, QCoreApplication.translate("MainWindow", u"VDC", None))

        self.groupBox_21.setTitle(QCoreApplication.translate("MainWindow", u"To Be Optimized", None))
        self.TorqueOpt.setText(QCoreApplication.translate("MainWindow", u"Maximize Gearbox Output Torque", None))
        self.EfficinecyOpt_min.setText(QCoreApplication.translate("MainWindow", u"Maximize Motor Efficiency (Min. Among Operating Points)", None))
        self.EfficinecyOpt_max.setText(QCoreApplication.translate("MainWindow", u"Maximize Motor Efficiency (Max. Among Operating Points)", None))
        self.WeightOpt.setText(QCoreApplication.translate("MainWindow", u"Minimize Motor Weight", None))
        self.MagWeightOpt.setText(QCoreApplication.translate("MainWindow", u"Minimize Magnet Material Volume", None))
        self.VoltageOpt.setText(QCoreApplication.translate("MainWindow", u"Minimize Phase Voltage", None))
        self.MtrLengthOpt.setText(QCoreApplication.translate("MainWindow", u"Minimize Motor Length", None))
        self.MtrRadiusOpt.setText(QCoreApplication.translate("MainWindow", u"Minimize Motor Radius", None))
        self.Execution.setText(QCoreApplication.translate("MainWindow", u"Execute Optimization", None))
#if QT_CONFIG(tooltip)
        self.progressBar.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.progressBar.setFormat(QCoreApplication.translate("MainWindow", u"%p% Progress", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Optimization", None))
        self.groupBox_22.setTitle(QCoreApplication.translate("MainWindow", u"Select Signals for Plotting", None))
        self.MinTrqMargin_Percent.setText(QCoreApplication.translate("MainWindow", u"Minimum Torque Margin", None))
        self.MeanTrqMargin_Percent.setText(QCoreApplication.translate("MainWindow", u"Average Torque Margin", None))
        self.MinEffMtr_Percent.setText(QCoreApplication.translate("MainWindow", u"Minimum Efficiency", None))
        self.MeanEffMtr_Percent.setText(QCoreApplication.translate("MainWindow", u"Average Efficiency", None))
        self.Weight_kg.setText(QCoreApplication.translate("MainWindow", u"Motor Weight", None))
        self.VDC_2.setText(QCoreApplication.translate("MainWindow", u"Phase Voltage", None))
        self.MagVol_m3.setText(QCoreApplication.translate("MainWindow", u"Magnet Volume", None))
        self.R_MtrLength_m.setText(QCoreApplication.translate("MainWindow", u"Motor Length", None))
        self.R_LaminatR_m.setText(QCoreApplication.translate("MainWindow", u"Motor Radius", None))
        self.MaxTotalLoss_W.setText(QCoreApplication.translate("MainWindow", u"Maximum Motor Loss", None))
        self.dropdown1.setItemText(0, QCoreApplication.translate("MainWindow", u"# of pole pairs", None))
        self.dropdown1.setItemText(1, QCoreApplication.translate("MainWindow", u"Radial length of magnet", None))
        self.dropdown1.setItemText(2, QCoreApplication.translate("MainWindow", u"Wire copper radius", None))
        self.dropdown1.setItemText(3, QCoreApplication.translate("MainWindow", u"Fill factor", None))
        self.dropdown1.setItemText(4, QCoreApplication.translate("MainWindow", u"Lamination tooth tip and wedge thickness", None))
        self.dropdown1.setItemText(5, QCoreApplication.translate("MainWindow", u"Lamination slot liner thickness", None))
        self.dropdown1.setItemText(6, QCoreApplication.translate("MainWindow", u"Gear ratio", None))
        self.dropdown1.setItemText(7, QCoreApplication.translate("MainWindow", u"Magnet backiron inner radius", None))
        self.dropdown1.setItemText(8, QCoreApplication.translate("MainWindow", u"Magnet backiron outer radius", None))
        self.dropdown1.setItemText(9, QCoreApplication.translate("MainWindow", u"Tooth width", None))
        self.dropdown1.setItemText(10, QCoreApplication.translate("MainWindow", u"Lamination tooth tip radius", None))
        self.dropdown1.setItemText(11, QCoreApplication.translate("MainWindow", u"Lamination slot radius", None))
        self.dropdown1.setItemText(12, QCoreApplication.translate("MainWindow", u"Magnet inner radius", None))
        self.dropdown1.setItemText(13, QCoreApplication.translate("MainWindow", u"Backiron thickness, lamination", None))
        self.dropdown1.setItemText(14, QCoreApplication.translate("MainWindow", u"Backiron thickness, magnet assembly", None))
        self.dropdown1.setItemText(15, QCoreApplication.translate("MainWindow", u"Lamination slot outer", None))
        self.dropdown1.setItemText(16, QCoreApplication.translate("MainWindow", u"Lamination slot area", None))
        self.dropdown1.setItemText(17, QCoreApplication.translate("MainWindow", u"Winding Slot area", None))
        self.dropdown1.setItemText(18, QCoreApplication.translate("MainWindow", u"Arc length of lamination ID", None))
        self.dropdown1.setItemText(19, QCoreApplication.translate("MainWindow", u"Arc length of one tooth pitch", None))
        self.dropdown1.setItemText(20, QCoreApplication.translate("MainWindow", u"Approx width of slot opening", None))
        self.dropdown1.setItemText(21, QCoreApplication.translate("MainWindow", u"# of turns", None))
        self.dropdown1.setItemText(22, QCoreApplication.translate("MainWindow", u"Actual flux density", None))
        self.dropdown1.setItemText(23, QCoreApplication.translate("MainWindow", u"Actual coil flux", None))
        self.dropdown1.setItemText(24, QCoreApplication.translate("MainWindow", u"Rated Torque per phase", None))
        self.dropdown1.setItemText(25, QCoreApplication.translate("MainWindow", u"Torque constant", None))
        self.dropdown1.setItemText(26, QCoreApplication.translate("MainWindow", u"BackEMF constant", None))
        self.dropdown1.setItemText(27, QCoreApplication.translate("MainWindow", u"Phase inductance", None))
        self.dropdown1.setItemText(28, QCoreApplication.translate("MainWindow", u"Phase resistance", None))
        self.dropdown1.setItemText(29, QCoreApplication.translate("MainWindow", u"Inertia", None))
        self.dropdown1.setItemText(30, QCoreApplication.translate("MainWindow", u"torque/inertia", None))
        self.dropdown1.setItemText(31, QCoreApplication.translate("MainWindow", u"Motor volume", None))
        self.dropdown1.setItemText(32, QCoreApplication.translate("MainWindow", u"Stator surface area", None))
        self.dropdown1.setItemText(33, QCoreApplication.translate("MainWindow", u"Fe weight", None))
        self.dropdown1.setItemText(34, QCoreApplication.translate("MainWindow", u"Cu weight", None))
        self.dropdown1.setItemText(35, QCoreApplication.translate("MainWindow", u"Rotor weight", None))
        self.dropdown1.setItemText(36, QCoreApplication.translate("MainWindow", u"Current density", None))
        self.dropdown1.setItemText(37, QCoreApplication.translate("MainWindow", u"Mean resistive losses", None))
        self.dropdown1.setItemText(38, QCoreApplication.translate("MainWindow", u"Mean back iron losses", None))
        self.dropdown1.setItemText(39, QCoreApplication.translate("MainWindow", u"Mean fluid losses", None))

        self.dropdown2.setItemText(0, QCoreApplication.translate("MainWindow", u"# of pole pairs", None))
        self.dropdown2.setItemText(1, QCoreApplication.translate("MainWindow", u"Radial length of magnet", None))
        self.dropdown2.setItemText(2, QCoreApplication.translate("MainWindow", u"Wire copper radius", None))
        self.dropdown2.setItemText(3, QCoreApplication.translate("MainWindow", u"Fill factor", None))
        self.dropdown2.setItemText(4, QCoreApplication.translate("MainWindow", u"Lamination tooth tip and wedge thickness", None))
        self.dropdown2.setItemText(5, QCoreApplication.translate("MainWindow", u"Lamination slot liner thickness", None))
        self.dropdown2.setItemText(6, QCoreApplication.translate("MainWindow", u"Gear ratio", None))
        self.dropdown2.setItemText(7, QCoreApplication.translate("MainWindow", u"Magnet backiron inner radius", None))
        self.dropdown2.setItemText(8, QCoreApplication.translate("MainWindow", u"Magnet backiron outer radius", None))
        self.dropdown2.setItemText(9, QCoreApplication.translate("MainWindow", u"Tooth width", None))
        self.dropdown2.setItemText(10, QCoreApplication.translate("MainWindow", u"Lamination tooth tip radius", None))
        self.dropdown2.setItemText(11, QCoreApplication.translate("MainWindow", u"Lamination slot radius", None))
        self.dropdown2.setItemText(12, QCoreApplication.translate("MainWindow", u"Magnet inner radius", None))
        self.dropdown2.setItemText(13, QCoreApplication.translate("MainWindow", u"Backiron thickness, lamination", None))
        self.dropdown2.setItemText(14, QCoreApplication.translate("MainWindow", u"Backiron thickness, magnet assembly", None))
        self.dropdown2.setItemText(15, QCoreApplication.translate("MainWindow", u"Lamination slot outer", None))
        self.dropdown2.setItemText(16, QCoreApplication.translate("MainWindow", u"Lamination slot area", None))
        self.dropdown2.setItemText(17, QCoreApplication.translate("MainWindow", u"Winding Slot area", None))
        self.dropdown2.setItemText(18, QCoreApplication.translate("MainWindow", u"Arc length of lamination ID", None))
        self.dropdown2.setItemText(19, QCoreApplication.translate("MainWindow", u"Arc length of one tooth pitch", None))
        self.dropdown2.setItemText(20, QCoreApplication.translate("MainWindow", u"Approx width of slot opening", None))
        self.dropdown2.setItemText(21, QCoreApplication.translate("MainWindow", u"# of turns", None))
        self.dropdown2.setItemText(22, QCoreApplication.translate("MainWindow", u"Actual flux density", None))
        self.dropdown2.setItemText(23, QCoreApplication.translate("MainWindow", u"Actual coil flux", None))
        self.dropdown2.setItemText(24, QCoreApplication.translate("MainWindow", u"Rated Torque per phase", None))
        self.dropdown2.setItemText(25, QCoreApplication.translate("MainWindow", u"Torque constant", None))
        self.dropdown2.setItemText(26, QCoreApplication.translate("MainWindow", u"BackEMF constant", None))
        self.dropdown2.setItemText(27, QCoreApplication.translate("MainWindow", u"Phase inductance", None))
        self.dropdown2.setItemText(28, QCoreApplication.translate("MainWindow", u"Phase resistance", None))
        self.dropdown2.setItemText(29, QCoreApplication.translate("MainWindow", u"Inertia", None))
        self.dropdown2.setItemText(30, QCoreApplication.translate("MainWindow", u"torque/inertia", None))
        self.dropdown2.setItemText(31, QCoreApplication.translate("MainWindow", u"Motor volume", None))
        self.dropdown2.setItemText(32, QCoreApplication.translate("MainWindow", u"Stator surface area", None))
        self.dropdown2.setItemText(33, QCoreApplication.translate("MainWindow", u"Fe weight", None))
        self.dropdown2.setItemText(34, QCoreApplication.translate("MainWindow", u"Cu weight", None))
        self.dropdown2.setItemText(35, QCoreApplication.translate("MainWindow", u"Rotor weight", None))
        self.dropdown2.setItemText(36, QCoreApplication.translate("MainWindow", u"Current density", None))
        self.dropdown2.setItemText(37, QCoreApplication.translate("MainWindow", u"Mean resistive losses", None))
        self.dropdown2.setItemText(38, QCoreApplication.translate("MainWindow", u"Mean back iron losses", None))
        self.dropdown2.setItemText(39, QCoreApplication.translate("MainWindow", u"Mean fluid losses", None))

        self.dropdown3.setItemText(0, QCoreApplication.translate("MainWindow", u"# of pole pairs", None))
        self.dropdown3.setItemText(1, QCoreApplication.translate("MainWindow", u"Radial length of magnet", None))
        self.dropdown3.setItemText(2, QCoreApplication.translate("MainWindow", u"Wire copper radius", None))
        self.dropdown3.setItemText(3, QCoreApplication.translate("MainWindow", u"Fill factor", None))
        self.dropdown3.setItemText(4, QCoreApplication.translate("MainWindow", u"Lamination tooth tip and wedge thickness", None))
        self.dropdown3.setItemText(5, QCoreApplication.translate("MainWindow", u"Lamination slot liner thickness", None))
        self.dropdown3.setItemText(6, QCoreApplication.translate("MainWindow", u"Gear ratio", None))
        self.dropdown3.setItemText(7, QCoreApplication.translate("MainWindow", u"Magnet backiron inner radius", None))
        self.dropdown3.setItemText(8, QCoreApplication.translate("MainWindow", u"Magnet backiron outer radius", None))
        self.dropdown3.setItemText(9, QCoreApplication.translate("MainWindow", u"Tooth width", None))
        self.dropdown3.setItemText(10, QCoreApplication.translate("MainWindow", u"Lamination tooth tip radius", None))
        self.dropdown3.setItemText(11, QCoreApplication.translate("MainWindow", u"Lamination slot radius", None))
        self.dropdown3.setItemText(12, QCoreApplication.translate("MainWindow", u"Magnet inner radius", None))
        self.dropdown3.setItemText(13, QCoreApplication.translate("MainWindow", u"Backiron thickness, lamination", None))
        self.dropdown3.setItemText(14, QCoreApplication.translate("MainWindow", u"Backiron thickness, magnet assembly", None))
        self.dropdown3.setItemText(15, QCoreApplication.translate("MainWindow", u"Lamination slot outer", None))
        self.dropdown3.setItemText(16, QCoreApplication.translate("MainWindow", u"Lamination slot area", None))
        self.dropdown3.setItemText(17, QCoreApplication.translate("MainWindow", u"Winding Slot area", None))
        self.dropdown3.setItemText(18, QCoreApplication.translate("MainWindow", u"Arc length of lamination ID", None))
        self.dropdown3.setItemText(19, QCoreApplication.translate("MainWindow", u"Arc length of one tooth pitch", None))
        self.dropdown3.setItemText(20, QCoreApplication.translate("MainWindow", u"Approx width of slot opening", None))
        self.dropdown3.setItemText(21, QCoreApplication.translate("MainWindow", u"# of turns", None))
        self.dropdown3.setItemText(22, QCoreApplication.translate("MainWindow", u"Actual flux density", None))
        self.dropdown3.setItemText(23, QCoreApplication.translate("MainWindow", u"Actual coil flux", None))
        self.dropdown3.setItemText(24, QCoreApplication.translate("MainWindow", u"Rated Torque per phase", None))
        self.dropdown3.setItemText(25, QCoreApplication.translate("MainWindow", u"Torque constant", None))
        self.dropdown3.setItemText(26, QCoreApplication.translate("MainWindow", u"BackEMF constant", None))
        self.dropdown3.setItemText(27, QCoreApplication.translate("MainWindow", u"Phase inductance", None))
        self.dropdown3.setItemText(28, QCoreApplication.translate("MainWindow", u"Phase resistance", None))
        self.dropdown3.setItemText(29, QCoreApplication.translate("MainWindow", u"Inertia", None))
        self.dropdown3.setItemText(30, QCoreApplication.translate("MainWindow", u"torque/inertia", None))
        self.dropdown3.setItemText(31, QCoreApplication.translate("MainWindow", u"Motor volume", None))
        self.dropdown3.setItemText(32, QCoreApplication.translate("MainWindow", u"Stator surface area", None))
        self.dropdown3.setItemText(33, QCoreApplication.translate("MainWindow", u"Fe weight", None))
        self.dropdown3.setItemText(34, QCoreApplication.translate("MainWindow", u"Cu weight", None))
        self.dropdown3.setItemText(35, QCoreApplication.translate("MainWindow", u"Rotor weight", None))
        self.dropdown3.setItemText(36, QCoreApplication.translate("MainWindow", u"Current density", None))
        self.dropdown3.setItemText(37, QCoreApplication.translate("MainWindow", u"Mean resistive losses", None))
        self.dropdown3.setItemText(38, QCoreApplication.translate("MainWindow", u"Mean back iron losses", None))
        self.dropdown3.setItemText(39, QCoreApplication.translate("MainWindow", u"Mean fluid losses", None))

        self.ParallelPlot.setText(QCoreApplication.translate("MainWindow", u"Parallel Plot", None))
        self.ThreeDPlot.setText(QCoreApplication.translate("MainWindow", u"3D Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Results", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

